/* Replace these two values with your Supabase project's public URL and anon key. */
const SUPABASE_URL = https://https://npvbkmkstwaheedvcxyb.supabase.co/rest/v1/;
const SUPABASE_ANON_KEY = sb_publishable_lsu8BBewMMNZ0Y-jagcFtA_c548G7Up;
const { createClient } = supabase;
const db = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
const $ = s => document.querySelector(s);
let user=null, profile=null, room='general', roomChannel=null, presenceChannel=null, authMode='signup', messages=[];
const rooms=[['general','General'],['gaming','Gaming'],['music','Music'],['creators','Creators'],['friends','Friends']];
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function initials(n){return (n||'?').trim().slice(0,1).toUpperCase()}
function time(v){return new Date(v).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}
function setConnection(t,ok=false){$('#connection').textContent=t;$('#connection').style.color=ok?'var(--green)':'var(--muted)'}
function renderRooms(){ $('#rooms').innerHTML=rooms.map(([id,label])=>`<div class="room ${id===room?'active':''}" data-room="${id}"><b># ${label}</b></div>`).join('');document.querySelectorAll('.room').forEach(x=>x.onclick=()=>switchRoom(x.dataset.room)); }
function renderMessages(){const box=$('#messages');if(!messages.length){box.innerHTML='<div class="empty">No messages yet. Start the conversation 👋</div>';return}box.innerHTML=messages.map(m=>{const mine=m.user_id===user.id;return `<div class="message ${mine?'mine':''}"><div class="avatar">${esc(initials(m.profiles?.display_name||'User'))}</div><div class="bubble-wrap"><div class="meta"><span class="name">${esc(m.profiles?.display_name||'User')}</span><span class="time">${time(m.created_at)}</span></div><div class="bubble">${esc(m.body)}</div></div></div>`}).join('');box.scrollTop=box.scrollHeight}
async function loadMessages(){const {data,error}=await db.from('messages').select('id,room,body,user_id,created_at,profiles(display_name)').eq('room',room).order('created_at',{ascending:true}).limit(200);if(error){console.error(error);return showError(error.message)}messages=data||[];renderMessages()}
async function subscribeRoom(){if(roomChannel)await db.removeChannel(roomChannel);roomChannel=db.channel('room:'+room).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`room=eq.${room}`},async payload=>{const {data}=await db.from('profiles').select('display_name').eq('id',payload.new.user_id).maybeSingle();messages.push({...payload.new,profiles:data||{display_name:'User'}});renderMessages()}).subscribe();}
async function switchRoom(next){room=next;$('#roomTitle').textContent='# '+room;$('#messageInput').placeholder='Message #'+room+'…';renderRooms();await loadMessages();await subscribeRoom()}
async function sendMessage(body){if(!body.trim()||!user)return;const {error}=await db.from('messages').insert({room,body:body.trim().slice(0,1000),user_id:user.id});if(error)showError(error.message)}
async function updateProfile(name){name=name.trim().slice(0,24);if(!name)return;const {error}=await db.from('profiles').upsert({id:user.id,display_name:name},{onConflict:'id'});if(error)return showError(error.message);profile.display_name=name;applyProfile();$('#modal').classList.remove('show');await publishPresence()}
function applyProfile(){const n=profile?.display_name||'User';$('#myName').textContent=n;$('#myAvatar').textContent=initials(n)}
async function publishPresence(){if(!presenceChannel)return;await presenceChannel.track({user_id:user.id,display_name:profile?.display_name||'User'})}
function renderPresence(){if(!presenceChannel)return;const state=presenceChannel.presenceState();const people=[];Object.values(state).forEach(arr=>arr.forEach(p=>{if(!people.some(x=>x.user_id===p.user_id))people.push(p)}));$('#onlineCount').textContent=`${people.length} ${people.length===1?'person':'people'} active`;$('#people').innerHTML=people.map(p=>`<div class="person"><div class="avatar">${esc(initials(p.display_name))}</div><div class="person-info"><div class="person-name">${esc(p.display_name)} ${p.user_id===user.id?'(you)':''}</div><div class="person-status">Online now</div></div><span class="dot"></span></div>`).join('')||'<div class="muted">No one else is online.</div>'}
async function setupPresence(){if(presenceChannel)await db.removeChannel(presenceChannel);presenceChannel=db.channel('presence:community',{config:{presence:{key:user.id}}}).on('presence',{event:'sync'},renderPresence).on('presence',{event:'join'},renderPresence).on('presence',{event:'leave'},renderPresence).subscribe(async status=>{if(status==='SUBSCRIBED'){setConnection('Live',true);await publishPresence();renderPresence()}})}
async function startApp(session){user=session.user;const {data}=await db.from('profiles').select('*').eq('id',user.id).maybeSingle();profile=data||{id:user.id,display_name:user.email?.split('@')[0]||'User'};$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');applyProfile();renderRooms();setConnection('Connecting…');await setupPresence();await loadMessages();await subscribeRoom()}
function showError(msg){$('#authError').textContent=msg||'Something went wrong.';if($('#appView')&&!$('#appView').classList.contains('hidden'))alert(msg)}
$('#authToggle').onclick=()=>{authMode=authMode==='signup'?'signin':'signup';$('#authTitle').textContent=authMode==='signup'?'Join the community':'Welcome back';$('#authSub').textContent=authMode==='signup'?'Create an account and start chatting with people anywhere.':'Sign in to continue your conversations.';$('#displayName').style.display=authMode==='signup'?'block':'none';$('#authToggle').textContent=authMode==='signup'?'Already have an account? Sign in':'New here? Create an account';$('#authError').textContent=''};
$('#authForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='';const email=$('#email').value.trim(),password=$('#password').value,displayName=$('#displayName').value.trim();let result;if(authMode==='signup'){result=await db.auth.signUp({email,password,options:{data:{display_name:displayName||email.split('@')[0]}}})}else result=await db.auth.signInWithPassword({email,password});if(result.error)return showError(result.error.message);if(authMode==='signup'&&!result.data.session){$('#authError').textContent='Check your email to confirm your account, then sign in.';return}if(result.data.session)await startApp(result.data.session)};
$('#chatForm').onsubmit=async e=>{e.preventDefault();const input=$('#messageInput');const v=input.value;input.value='';await sendMessage(v)};
$('#logoutBtn').onclick=async()=>{if(presenceChannel)await db.removeChannel(presenceChannel);if(roomChannel)await db.removeChannel(roomChannel);await db.auth.signOut();location.reload()};
$('#profileBtn').onclick=()=>{$('#nameInput').value=profile?.display_name||'';$('#modal').classList.add('show');$('#nameInput').focus()};$('#cancelBtn').onclick=()=>$('#modal').classList.remove('show');$('#saveBtn').onclick=()=>updateProfile($('#nameInput').value);
$('#inviteBtn').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('#inviteBtn').textContent='Copied!';setTimeout(()=>$('#inviteBtn').textContent='Invite',1200)}catch{prompt('Copy this invite link:',location.href)}};
db.auth.onAuthStateChange(async(_event,session)=>{if(session&&!user)await startApp(session)});
(async()=>{if(SUPABASE_URL.includes('YOUR-PROJECT')){document.querySelector('#authTitle').textContent='Connect is ready to deploy';document.querySelector('#authSub').textContent='Add your Supabase URL and anon key in app.js, then open this site.';return}const {data}=await db.auth.getSession();if(data.session)await startApp(data.session)})();
